In [1]:
import xlrd
import pymysql
import math
import pandas as pd
from sqlalchemy import create_engine

In [3]:
conn = pymysql.connect(
        host='localhost', 
        user='root', 
        passwd = 'fc117108',
        db='music',
        port=3306,
        charset='utf8'
        )
cur = conn.cursor()
cur.execute("SET NAMES utf8")

sql_cmd = "SELECT distinct album_id,album_name,singer_id,years,months,album_language,album_song,compancy FROM music.Excel20;"
df = pd.read_sql(sql_cmd,conn)
df

,album_id,album_name,singer_id,years,months,album_language,album_song,compancy
0,10019802,整個給你,100198,1993,01,國語,10,滾石
1,100198010,祭文,100198,1987,09,國語,9,喜馬拉雅
2,100198012,全世界只有你不知道[新歌+精選跨時空情歌全集],100198,2004,04,國語,20,滾石
3,10019806,情定日落橋,100198,1997,11,國語,17,滾石
4,100198011,滾石香港黃金十年,100198,2003,03,國語,15,滾石
...,...,...,...,...,...,...,...,...
37341,10500101,痛徹心扉,105001,未記錄,未記錄,未記錄,1,未記錄
37342,10500102,朝代,105001,未記錄,未記錄,未記錄,1,未記錄
37343,10500103,愛情的樂章,105001,未記錄,未記錄,未記錄,1,未記錄
37344,10500104,你離開的事實,105001,未記錄,未記錄,未記錄,1,未記錄
37345,10500106,暫存,105001,未記錄,未記錄,未記錄,1,未記錄

In [4]:
# cur.close() 
conn = create_engine('mysql+pymysql://root:fc117108@localhost:3306/mojim',encoding='utf8')  

pd.io.sql.to_sql(df, "album", conn,index=False, if_exists='replace')