In [2]:
import xlrd
import pymysql
import math
import pandas as pd
from sqlalchemy import create_engine
from bs4 import BeautifulSoup 
import requests 
import re 
import random

In [3]:
conn = pymysql.connect(
        host='localhost', 
        user='root', 
        passwd = 'fc117108',
        db='music',
        port=3306,
        charset='utf8'
        )
cur = conn.cursor()
cur.execute("SET NAMES utf8")

sql_cmd = "SELECT distinct singer_id,singer_name,id,link FROM music.Excel10;"
df = pd.read_sql(sql_cmd,conn)
df

/usr/local/lib/python3.7/site-packages/pymysql/cursors.py:170: Warning: (3719, "'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.")
  result = self._query(query)

        singer_id singer_name      id                                 link
0          100198         張洪量  100000  https://mojim.com/twy100198x2x2.htm
1          100198         張洪量  100002  https://mojim.com/twy100198x2x4.htm
2          100198         張洪量  100005  https://mojim.com/twy100198x2x7.htm
3          100198         張洪量  100006  https://mojim.com/twy100198x2x8.htm
4          100198         張洪量  100007  https://mojim.com/twy100198x2x9.htm
...           ...         ...     ...                                  ...
261484     105001      網友音樂創作  293084  https://mojim.com/twy105001x1x1.htm
261485     105001      網友音樂創作  293085  https://mojim.com/twy105001x2x1.htm
261486     105001      網友音樂創作  293086  https://mojim.com/twy105001x3x1.htm
261487     105001      網友音樂創作  293087  https://mojim.com/twy105001x4x1.htm
261488     105001      網友音樂創作  293088  https://mojim.com/twy105001x6x1.htm

[261489 rows x 4 columns]

In [4]:
df1=df[['singer_id','singer_name']].drop_duplicates()
data_dict=df1.to_dict('records')
print(len(data_dict))
print(data_dict[0])
indices=dict()

for doc in data_dict[:]:
#     print(doc)
   
        if doc['singer_id'] not in indices:
            indices[doc['singer_id']]=[]
        indices[doc['singer_id']].append(str(doc['singer_name']))
# indices



list_key_values=[[k,v] for k ,v in indices.items()]

df_if=pd.DataFrame.from_dict(list_key_values)
df_if.columns=['singer_id','singer_name']


df_if['count']=[len(l) for l in df_if.singer_name] 
df_if=df_if.sort_values('count')
df_if[df_if['count']>1]

9099
{'singer_id': 100198, 'singer_name': '張洪量'}

      singer_id                                        singer_name  count
3041     106737                                         [兄弟小文, 小文]      2
101      104757                                 [陳好, 陳好(Chen Hao)]      2
7072     172256                             [黃禮格(Hoo Leeger), 黃禮格]      2
999      154699                                 [The One 鄭淳元, 鄭淳元]      2
2132     104644                                         [人工衛星, 圈圈]      2
...         ...                                                ...    ...
2776     124806  [16 個夏天, 微時代之戀, 電視原聲帶(2014), 徵婚啟事, 我的自由年代, 巷弄裡...     49
1808     180933  [經典特調 II, 合輯(2017年發行), 台商最愛聽的歌, 華人碉堡音樂帝國, MY A...     52
3120     161281  [滾石愛情故事, Younha, Various Artists, 好先生, Zia, 美人...     57
998      181695  [我的電視劇情歌集, Various Artists, 최강배달꾼, 稍息立正我愛你, 愛不...     63
2758     161021  [眾藝人, 情歌(LOVE), Various Artists, 阿爾發全體藝人, 合輯(2...     70

[282 rows x 3 columns]

In [5]:
singerid=df_if[df_if['count']>1].singer_id.tolist()

In [6]:
# conn = pymysql.connect(
#         host='localhost', 
#         user='root', 
#         passwd = 'fc117108',
#         db='music',
#         port=3306,
#         charset='utf8'
#         )
# cur = conn.cursor()

# for i in singerid[:]:
#     singer=str(i)
# #     print(i,singer)
#     url = 'https://mojim.com/twh'+singer+'.htm'
# #     print('url',url)
#     resp = requests.get(url)
#     soup = BeautifulSoup(resp.text, 'html.parser')
#     txt2=soup.find_all('a',href=True)

#     for j in txt2:
#         if j['href']==url:
#             singer_name=j.string
    
#             values=[i,singer_name]
# #                 sql = "INSERT IGNORE INTO new_singer_name (id,singer, title,url,top) VALUES (%s, %s, %s, %s, %s)"
#             sql = "INSERT IGNORE INTO new_singer (singer_id,singer_name) VALUES (%s, %s)"
#             cur.execute(sql, values)
#             conn.commit()
# conn.close()

In [8]:
conn = pymysql.connect(
        host='localhost', 
        user='root', 
        passwd = 'fc117108',
        db='music',
        port=3306,
        charset='utf8'
        )
cur = conn.cursor()
cur.execute("SET NAMES utf8")

sql_cmd = "SELECT * FROM music.Excel10;"
df1 = pd.read_sql(sql_cmd,conn)



sql_cmd = "SELECT * FROM music.new_singer;"
df2 = pd.read_sql(sql_cmd,conn)
df2.head(20)

/usr/local/lib/python3.7/site-packages/pymysql/cursors.py:170: Warning: (3719, "'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.")
  result = self._query(query)

    singer_id                       new_name
0      100025                            伊雪莉
1      100043         Super Junior-M( SJ-M )
2      100070                      阿雅( 柳翰雅 )
3      100080               馬浚偉( Steven Ma )
4      100084                    庾澄慶( 頂尖拍檔 )
5      100087                      張信哲( 阿哲 )
6      100090                      張惠妹( 阿妹 )
7      100097                脫拉庫樂團( TOLAKU )
8      100126                游鴻明( Chris Yu )
9      100158                劉若英( Rene Liu )
10     100167                     朱頭皮( 豬頭皮 )
11     100186                孫建平( 孫建平&音樂廣場 )
12     100206                羅百吉( Jerry Lo )
13     100255            潘越雲( Michelle Pan )
14     100264             黃鶯鶯( Tracy Huang )
15     100309                   林隆璇( Kevin )
16     100384  唐朝樂隊( The Tang Dynasty Band )
17     100430                           校園歌曲
18     100587           劉美君( Prudence Liew )
19     100602                   Gary麟( 蔡興麟 )

In [10]:
id1=[110509, 136124, 109442, 124806, 180933, 161281, 181695, 161021]
df2[df2['singer_id'].isin(id1)]

     singer_id     new_name
146     109442  合輯(2011年發行)
162     110509  合輯(2012年發行)
199     124806  電視原聲帶(2014)
223     136124  電視原聲帶(2015)
244     161021  合輯(2016年發行)
245     161281  電視原聲帶(2016)
271     180933  合輯(2017年發行)
274     181695  電視原聲帶(2017)

In [26]:
df3=df1[['singer_id','singer_name']]
# print(len(df5))

In [27]:
df3=df3[df3['singer_id'].isin(singerid)]
df4=pd.merge(df2,df3,on='singer_id',how='outer')
df4

       singer_id                 new_name singer_name
0         100025                      伊雪莉         伊雪莉
1         100025                      伊雪莉         伊雪莉
2         100025                      伊雪莉         伊雪莉
3         100025                      伊雪莉         伊雪莉
4         100025                      伊雪莉         伊雪莉
...          ...                      ...         ...
28519     188684  廚子和戲子( CHEF and ACTOR )       廚子和戲子
28520     188684  廚子和戲子( CHEF and ACTOR )       廚子和戲子
28521     188684  廚子和戲子( CHEF and ACTOR )       廚子和戲子
28522     188684  廚子和戲子( CHEF and ACTOR )       廚子和戲子
28523     188684  廚子和戲子( CHEF and ACTOR )     廚子 、 戲子

[28524 rows x 3 columns]

In [28]:
df4.loc[df4['new_name'].values!=df4['singer_name'].values,'singer_name']=df4.new_name

df4[df4['new_name'].values!=df4['singer_name'].values]

Empty DataFrame
Columns: [singer_id, new_name, singer_name]
Index: []

In [29]:
df4[df4['new_name'].values==df4['singer_name'].values]
df6=df4[['singer_id','singer_name']]
df6

       singer_id              singer_name
0         100025                      伊雪莉
1         100025                      伊雪莉
2         100025                      伊雪莉
3         100025                      伊雪莉
4         100025                      伊雪莉
...          ...                      ...
28519     188684  廚子和戲子( CHEF and ACTOR )
28520     188684  廚子和戲子( CHEF and ACTOR )
28521     188684  廚子和戲子( CHEF and ACTOR )
28522     188684  廚子和戲子( CHEF and ACTOR )
28523     188684  廚子和戲子( CHEF and ACTOR )

[28524 rows x 2 columns]

In [30]:
df7=pd.merge(df1,df6,on='singer_id',how='outer')
df7

,id,link,class,singer_id,singer_name_x,group_id,song_id,song_name,song_word,album_id,...,album_language,album_song,years,month,lyric_id,same_id,lyric_language,author_name,composer_name,singer_name_y
0,100000,https://mojim.com/twy100198x2x2.htm,男生歌手,100198,張洪量,0.0,1001980202,情為何物,4,10019802,...,國語,10,1993,1,100000,100000,Chinese,張洪量,張洪量,NaN
1,100002,https://mojim.com/twy100198x2x4.htm,男生歌手,100198,張洪量,0.0,1001980204,浮萍,2,10019802,...,國語,10,1993,1,100002,100002,Chinese,張洪量,張洪量,NaN
2,100005,https://mojim.com/twy100198x2x7.htm,男生歌手,100198,張洪量,0.0,1001980207,沙漠之花,4,10019802,...,國語,10,1993,1,100005,100005,Chinese,張洪量,張洪量,NaN
3,100006,https://mojim.com/twy100198x2x8.htm,男生歌手,100198,張洪量,0.0,1001980208,我想我瘋了,5,10019802,...,國語,10,1993,1,100006,100006,Chinese,張洪量,張洪量,NaN
4,100007,https://mojim.com/twy100198x2x9.htm,男生歌手,100198,張洪量,0.0,1001980209,外星戀,3,10019802,...,國語,10,1993,1,100007,100007,Chinese,張洪量,張洪量,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13019426,293084,https://mojim.com/twy105001x1x1.htm,其他歌手,105001,網友音樂創作,0.0,1050010101,痛徹心扉(孫培恩),4,10500101,...,國語,1,未知,未知,293084,293084,Chinese,未知,未知,NaN
13019427,293085,https://mojim.com/twy105001x2x1.htm,其他歌手,105001,網友音樂創作,0.0,1050010201,朝代,2,10500102,...,國語,1,未知,未知,293085,293085,Chinese,口香糖,未知,NaN
13019428,293086,https://mojim.com/twy105001x3x1.htm,其他歌手,105001,網友音樂創作,0.0,1050010301,愛情的樂章,5,10500103,...,國語,1,未知,未知,293086,293086,Chinese,未知,未知,NaN
13019429,293087,https://mojim.com/twy105001x4x1.htm,其他歌手,105001,網友音樂創作,0.0,1050010401,妳離開的事實,6,10500104,...,國語,1,未知,未知,293087,293087,Chinese,小凱,PianoBoy(The truth that you leave),NaN
13019430,293088,https://mojim.com/twy105001x6x1.htm,其他歌手,105001,網友音樂創作,0.0,1050010601,分開的最後一天,7,10500106,...,國語,1,未知,未知,293088,293088,Chinese,未知,未知,NaN

In [31]:
df7=df7.fillna(0)
df7[df7['singer_name_y']==0]

,id,link,class,singer_id,singer_name_x,group_id,song_id,song_name,song_word,album_id,...,album_language,album_song,years,month,lyric_id,same_id,lyric_language,author_name,composer_name,singer_name_y
0,100000,https://mojim.com/twy100198x2x2.htm,男生歌手,100198,張洪量,0.0,1001980202,情為何物,4,10019802,...,國語,10,1993,1,100000,100000,Chinese,張洪量,張洪量,0
1,100002,https://mojim.com/twy100198x2x4.htm,男生歌手,100198,張洪量,0.0,1001980204,浮萍,2,10019802,...,國語,10,1993,1,100002,100002,Chinese,張洪量,張洪量,0
2,100005,https://mojim.com/twy100198x2x7.htm,男生歌手,100198,張洪量,0.0,1001980207,沙漠之花,4,10019802,...,國語,10,1993,1,100005,100005,Chinese,張洪量,張洪量,0
3,100006,https://mojim.com/twy100198x2x8.htm,男生歌手,100198,張洪量,0.0,1001980208,我想我瘋了,5,10019802,...,國語,10,1993,1,100006,100006,Chinese,張洪量,張洪量,0
4,100007,https://mojim.com/twy100198x2x9.htm,男生歌手,100198,張洪量,0.0,1001980209,外星戀,3,10019802,...,國語,10,1993,1,100007,100007,Chinese,張洪量,張洪量,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13019426,293084,https://mojim.com/twy105001x1x1.htm,其他歌手,105001,網友音樂創作,0.0,1050010101,痛徹心扉(孫培恩),4,10500101,...,國語,1,未知,未知,293084,293084,Chinese,未知,未知,0
13019427,293085,https://mojim.com/twy105001x2x1.htm,其他歌手,105001,網友音樂創作,0.0,1050010201,朝代,2,10500102,...,國語,1,未知,未知,293085,293085,Chinese,口香糖,未知,0
13019428,293086,https://mojim.com/twy105001x3x1.htm,其他歌手,105001,網友音樂創作,0.0,1050010301,愛情的樂章,5,10500103,...,國語,1,未知,未知,293086,293086,Chinese,未知,未知,0
13019429,293087,https://mojim.com/twy105001x4x1.htm,其他歌手,105001,網友音樂創作,0.0,1050010401,妳離開的事實,6,10500104,...,國語,1,未知,未知,293087,293087,Chinese,小凱,PianoBoy(The truth that you leave),0
13019430,293088,https://mojim.com/twy105001x6x1.htm,其他歌手,105001,網友音樂創作,0.0,1050010601,分開的最後一天,7,10500106,...,國語,1,未知,未知,293088,293088,Chinese,未知,未知,0

In [32]:
df7.loc[df7['singer_name_y']==0,'singer_name_y']=df7.singer_name_x


df7[df7['singer_name_y']==0]

Empty DataFrame
Columns: [id, link, class, singer_id, singer_name_x, group_id, song_id, song_name, song_word, album_id, album_name, album_language, album_song, years, month, lyric_id, same_id, lyric_language, author_name, composer_name, singer_name_y]
Index: []

[0 rows x 21 columns]

In [33]:
df7=df7.drop('singer_name_x',1)
df7.head(2)

,id,link,class,singer_id,group_id,song_id,song_name,song_word,album_id,album_name,album_language,album_song,years,month,lyric_id,same_id,lyric_language,author_name,composer_name,singer_name_y
0,100000,https://mojim.com/twy100198x2x2.htm,男生歌手,100198,0.0,1001980202,情為何物,4,10019802,整個給你,國語,10,1993,1,100000,100000,Chinese,張洪量,張洪量,張洪量
1,100002,https://mojim.com/twy100198x2x4.htm,男生歌手,100198,0.0,1001980204,浮萍,2,10019802,整個給你,國語,10,1993,1,100002,100002,Chinese,張洪量,張洪量,張洪量

In [34]:
df7.rename(columns = {'singer_name_y':'singer_name'}, inplace = True) 
df7

,id,link,class,singer_id,group_id,song_id,song_name,song_word,album_id,album_name,album_language,album_song,years,month,lyric_id,same_id,lyric_language,author_name,composer_name,singer_name
0,100000,https://mojim.com/twy100198x2x2.htm,男生歌手,100198,0.0,1001980202,情為何物,4,10019802,整個給你,國語,10,1993,1,100000,100000,Chinese,張洪量,張洪量,張洪量
1,100002,https://mojim.com/twy100198x2x4.htm,男生歌手,100198,0.0,1001980204,浮萍,2,10019802,整個給你,國語,10,1993,1,100002,100002,Chinese,張洪量,張洪量,張洪量
2,100005,https://mojim.com/twy100198x2x7.htm,男生歌手,100198,0.0,1001980207,沙漠之花,4,10019802,整個給你,國語,10,1993,1,100005,100005,Chinese,張洪量,張洪量,張洪量
3,100006,https://mojim.com/twy100198x2x8.htm,男生歌手,100198,0.0,1001980208,我想我瘋了,5,10019802,整個給你,國語,10,1993,1,100006,100006,Chinese,張洪量,張洪量,張洪量
4,100007,https://mojim.com/twy100198x2x9.htm,男生歌手,100198,0.0,1001980209,外星戀,3,10019802,整個給你,國語,10,1993,1,100007,100007,Chinese,張洪量,張洪量,張洪量
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13019426,293084,https://mojim.com/twy105001x1x1.htm,其他歌手,105001,0.0,1050010101,痛徹心扉(孫培恩),4,10500101,痛徹心扉,國語,1,未知,未知,293084,293084,Chinese,未知,未知,網友音樂創作
13019427,293085,https://mojim.com/twy105001x2x1.htm,其他歌手,105001,0.0,1050010201,朝代,2,10500102,朝代,國語,1,未知,未知,293085,293085,Chinese,口香糖,未知,網友音樂創作
13019428,293086,https://mojim.com/twy105001x3x1.htm,其他歌手,105001,0.0,1050010301,愛情的樂章,5,10500103,愛情的樂章,國語,1,未知,未知,293086,293086,Chinese,未知,未知,網友音樂創作
13019429,293087,https://mojim.com/twy105001x4x1.htm,其他歌手,105001,0.0,1050010401,妳離開的事實,6,10500104,你離開的事實,國語,1,未知,未知,293087,293087,Chinese,小凱,PianoBoy(The truth that you leave),網友音樂創作
13019430,293088,https://mojim.com/twy105001x6x1.htm,其他歌手,105001,0.0,1050010601,分開的最後一天,7,10500106,分開的最後一天,國語,1,未知,未知,293088,293088,Chinese,未知,未知,網友音樂創作

In [35]:
df7.drop_duplicates(inplace = True)
df7

,id,link,class,singer_id,group_id,song_id,song_name,song_word,album_id,album_name,album_language,album_song,years,month,lyric_id,same_id,lyric_language,author_name,composer_name,singer_name
0,100000,https://mojim.com/twy100198x2x2.htm,男生歌手,100198,0.0,1001980202,情為何物,4,10019802,整個給你,國語,10,1993,1,100000,100000,Chinese,張洪量,張洪量,張洪量
1,100002,https://mojim.com/twy100198x2x4.htm,男生歌手,100198,0.0,1001980204,浮萍,2,10019802,整個給你,國語,10,1993,1,100002,100002,Chinese,張洪量,張洪量,張洪量
2,100005,https://mojim.com/twy100198x2x7.htm,男生歌手,100198,0.0,1001980207,沙漠之花,4,10019802,整個給你,國語,10,1993,1,100005,100005,Chinese,張洪量,張洪量,張洪量
3,100006,https://mojim.com/twy100198x2x8.htm,男生歌手,100198,0.0,1001980208,我想我瘋了,5,10019802,整個給你,國語,10,1993,1,100006,100006,Chinese,張洪量,張洪量,張洪量
4,100007,https://mojim.com/twy100198x2x9.htm,男生歌手,100198,0.0,1001980209,外星戀,3,10019802,整個給你,國語,10,1993,1,100007,100007,Chinese,張洪量,張洪量,張洪量
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13019426,293084,https://mojim.com/twy105001x1x1.htm,其他歌手,105001,0.0,1050010101,痛徹心扉(孫培恩),4,10500101,痛徹心扉,國語,1,未知,未知,293084,293084,Chinese,未知,未知,網友音樂創作
13019427,293085,https://mojim.com/twy105001x2x1.htm,其他歌手,105001,0.0,1050010201,朝代,2,10500102,朝代,國語,1,未知,未知,293085,293085,Chinese,口香糖,未知,網友音樂創作
13019428,293086,https://mojim.com/twy105001x3x1.htm,其他歌手,105001,0.0,1050010301,愛情的樂章,5,10500103,愛情的樂章,國語,1,未知,未知,293086,293086,Chinese,未知,未知,網友音樂創作
13019429,293087,https://mojim.com/twy105001x4x1.htm,其他歌手,105001,0.0,1050010401,妳離開的事實,6,10500104,你離開的事實,國語,1,未知,未知,293087,293087,Chinese,小凱,PianoBoy(The truth that you leave),網友音樂創作
13019430,293088,https://mojim.com/twy105001x6x1.htm,其他歌手,105001,0.0,1050010601,分開的最後一天,7,10500106,分開的最後一天,國語,1,未知,未知,293088,293088,Chinese,未知,未知,網友音樂創作

In [36]:
# cur.close() 
conn = create_engine('mysql+pymysql://root:fc117108@localhost:3306/music',encoding='utf8')  

pd.io.sql.to_sql(df7, "Excel11", conn,index=False, if_exists='replace')